# Generated by Django 4.0 on 2022-02-19 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_delete_notificationusersaboutblocking'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationUsersFromModerator',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.basemodel')),
                ('moderator', models.UUIDField(verbose_name='модератор')),
                ('is_read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('message', models.CharField(blank=True, max_length=500, null=True, verbose_name='уведомление')),
                ('recipient_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.user', verbose_name='получатель уведомления')),
            ],
            bases=('mainapp.basemodel',),
        ),
    ]
