# Generated by Django 4.0 on 2022-02-20 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_delete_notificationusersaboutblocking'),
        ('mainapp', '0002_notificationusersfrommoderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorNotificationAboutReModeration',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.basemodel')),
                ('status', models.CharField(choices=[('N', 'Новая'), ('A', 'Назначена'), ('U', 'На рассмотрении'), ('R', 'Рассмотрена')], default='N', max_length=1, verbose_name='Статус')),
                ('article_for_re_moderation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_for_re_moderation', to='mainapp.article', verbose_name='Статья для повторной модерации')),
                ('responsible_moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsible_article_moderator', to='authapp.user', verbose_name='Ответственный модератор')),
            ],
            options={
                'db_table': 'moderator_notification_about_re_moderation',
                'ordering': ['-created_timestamp'],
            },
            bases=('mainapp.basemodel',),
        ),
    ]
