# Generated by Django 4.0 on 2022-02-23 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_delete_notificationusersaboutblocking'),
        ('mainapp', '0003_moderatornotificationaboutremoderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyComments',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.basemodel')),
                ('text', models.TextField(max_length=200, verbose_name='ReplyComment Text')),
                ('comment_to_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_to_reply', to='mainapp.articlecomment', verbose_name='Comment to reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment_author', to='authapp.user', verbose_name='ReplyComment Author')),
            ],
            options={
                'ordering': ['-created_timestamp'],
            },
            bases=('mainapp.basemodel',),
        ),
        migrations.CreateModel(
            name='NotificationUserAfterLikeAndComment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.basemodel')),
                ('sender_notification', models.UUIDField(verbose_name='отправитель уведомления')),
                ('is_read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('message', models.CharField(blank=True, max_length=200, null=True, verbose_name='уведомление')),
                ('recipient_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.user', verbose_name='получатель уведомления')),
            ],
            bases=('mainapp.basemodel',),
        ),
    ]
