# Generated by Django 4.0 on 2022-04-03 19:32

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCategories',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('Category', models.CharField(max_length=100, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категории доступа',
                'db_table': 'wdcnext_access_categories',
            },
        ),
        migrations.CreateModel(
            name='BusinessDirections',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('direction', models.CharField(max_length=100, verbose_name='Наименование направления')),
            ],
            options={
                'verbose_name': 'Таблица Напровлений бизнеса(департаменты)',
                'db_table': 'wdcnext_business_directions',
            },
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('specialization', models.CharField(max_length=100, verbose_name='Наименование специализации')),
            ],
            options={
                'verbose_name': 'Таблица Специализации',
                'db_table': 'wdcnext_specializations',
            },
        ),
        migrations.CreateModel(
            name='TypeOfPage',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('type_of_page', models.CharField(max_length=100, verbose_name='Тип страницы')),
            ],
            options={
                'verbose_name': 'Таблица Типы страницы(лендинга)',
                'db_table': 'wdcnext_type_of_page',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('header', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Символьный код страницы')),
                ('active', models.BooleanField(db_index=True, default=False, verbose_name='Активен')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало эксплуатации')),
                ('date_end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Окончание эксплуатации')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Код страницы HTML')),
                ('tags', models.JSONField(blank=True, null=True, verbose_name='Теги')),
                ('seo_title', models.CharField(blank=True, max_length=120, null=True, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO description')),
                ('sending_addresses', models.JSONField(verbose_name='Адреса отправки заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('business_direction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='page', to='pages.businessdirections', verbose_name='Направление бизнеса')),
                ('page_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.typeofpage', verbose_name='Тип лэндинга')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='page', to='pages.specializations', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Таблица страниц сайта (лендинги)',
                'db_table': 'wdcnext_pages',
            },
        ),
    ]
