# Generated by Django 4.0 on 2022-02-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationUsersAboutBlocking',
        ),
    ]
